### ISSUE TITLE
Cannot find module './lib/helpers'

### ISSUE THREAD

**Issue by sichvoge** [mulesoft-labs/raml-generator#2]
If I execute my app using the `raml-generator` module - I get this exception:

``` javascript
Error: Cannot find module './lib/helpers'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/christianmule/node_modules/raml-generator/raml-generator.js:4:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Can it be that it tries to find the module inside the execution folder?

**Comment by blakeembrey** [comment]
And this is what happens when you publish something hours before the flight - lucky it's delayed and I can fix this :stuck_out_tongue_closed_eyes: Patched with `v0.0.3`
